export const MODULES = [
  { path: '/', label: 'Resumen' },
  { path: '/events', label: 'Eventos' },
  { path: '/people', label: 'Personas' },
  { path: '/accreditations', label: 'Acreditaciones' },
  { path: '/accreditation-facial', label: 'Acreditación facial' },
  { path: '/access-control', label: 'Control de acceso' },
  { path: '/access-monitor', label: 'Monitor en vivo' },
  { path: '/zkteco-devices', label: 'Terminales ZKTeco' },
  { path: '/reports', label: 'Reportes' },
  { path: '/messages', label: 'Mensajes' },
  { path: '/documents', label: 'Documentos' },
  { path: '/registered-people', label: 'Personas registradas' },
  { path: '/registered-vehicles', label: 'Vehículos registrados' },
  { path: '/vehicles', label: 'Vehículos' },
  { path: '/users', label: 'Usuarios y roles' },
  { path: '/audit', label: 'Auditoría' },
  { path: '/settings', label: 'Configuración' },
];

export const ROLES = ['control', 'coordinator', 'productora', 'admin', 'superadmin'];

export const DEFAULT_ROLE_ACCESS = {
  '/': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/events': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/people': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/accreditations': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/accreditation-facial': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/access-control': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/access-monitor': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/zkteco-devices': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/reports': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/messages': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/documents': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/registered-people': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/registered-vehicles': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/vehicles': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/users': ['admin', 'superadmin'],
  '/audit': ['admin', 'superadmin'],
  '/settings': ['admin', 'superadmin'],
};