export const MODULES = [
  { path: '/', label: 'Resumen' },
  { path: '/events', label: 'Eventos' },
  { path: '/people', label: 'Empleados' },
  { path: '/dni-scan', label: 'Escaneo DNI' },
  { path: '/personas-autonomas', label: 'Personas Autónomas' },
  { path: '/provider-companies', label: 'Empresas proveedoras' },
  { path: '/accreditations', label: 'Acreditaciones' },
  { path: '/personal-acreditado', label: 'Personal acreditado' },
  { path: '/access-levels', label: 'Niveles de acceso' },
  { path: '/accreditation-facial', label: 'Acreditación facial' },
  { path: '/access-control', label: 'Control de acceso' },
  { path: '/pda-id', label: 'PDA ID' },
  { path: '/emergency-scan', label: 'Emergencia' },
  { path: '/access-monitor', label: 'Monitor en vivo' },
  { path: '/pda-stations', label: 'Estaciones PDA' },
  { path: '/zkteco-devices', label: 'Terminales ZKTeco' },
  { path: '/reports', label: 'Reportes' },
  { path: '/messages', label: 'Mensajes' },
  { path: '/documents', label: 'Documentos' },
  { path: '/registered-people', label: 'Personas registradas' },
  { path: '/registered-vehicles', label: 'Vehículos registrados' },
  { path: '/vehicles', label: 'Vehículos acreditados' },
  { path: '/parking-sectors', label: 'Estacionamiento' },
  { path: '/companies', label: 'Empresas' },
  { path: '/users', label: 'Usuarios y roles' },
  { path: '/audit', label: 'Auditoría' },
  { path: '/settings', label: 'Configuración' },
];

export const ROLES = ['provider', 'empresa', 'control', 'coordinator', 'productora', 'admin', 'superadmin'];

export const DEFAULT_ROLE_ACCESS = {
  '/': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/events': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/people': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/dni-scan': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/personas-autonomas': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/provider-companies': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/accreditations': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/personal-acreditado': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/access-levels': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/accreditation-facial': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/access-control': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/pda-id': ['control', 'operador', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/emergency-scan': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/access-monitor': ['control', 'coordinator', 'productora', 'admin', 'superadmin'],
  '/pda-stations': ['productora', 'admin', 'superadmin'],
  '/zkteco-devices': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/reports': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/messages': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/documents': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/registered-people': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/registered-vehicles': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/vehicles': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/parking-sectors': ['coordinator', 'productora', 'admin', 'superadmin'],
  '/companies': ['productora', 'admin', 'superadmin'],
  '/users': ['admin', 'superadmin'],
  '/audit': ['admin', 'superadmin'],
  '/settings': ['admin', 'superadmin'],
};